apiVersion: apps/v1
kind: Deployment
metadata:
  name: restapi-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restapi-service
  template:
    metadata:
      labels:
        app: restapi-service
    spec:
      containers:
        - name: restapi-service
          image: daegon7/msa-restapi-app:latest
          ports:
            - containerPort: 8082
          env:
            - name: EUREKA_URI
              value: http://eureka-server:8761/eureka
            - name: SPRING_APPLICATION_NAME
              value: restapi-service
            - name: SERVER_PORT
              value: "8082"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://host.docker.internal:3306/sampledb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: YourStrong@Passw0rd
            - name: SPRING_DATA_REDIS_HOST
              value: host.docker.internal
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"
            - name: SPRING_DATA_REDIS_PASSWORD
              value: yourStrongPassword